import "../styles/globals.css"; // Importamos los estilos globales de la aplicación.

import "react-toastify/dist/ReactToastify.css"; // Importamos los estilos de React Toastify el cual te permite agregar notificaciones a tu aplicación de forma sencilla.

import { Inter } from "next/font/google"; // Importamos la fuente Inter de Google Fonts.

// Claramente a estas alturasa del tutorial, estos componentes no existen, pero los crearemos más adelante.
import Header from "@/components/header";
import Footer from "@/components/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  // Configuramos los metadatos de la aplicación, esto es para SEO.
  title: "Tailblocks Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}